### ISSUE TITLE
error: ISO C++ forbids in-class initialization of non-const static member 'Object::commentMangledSymbol'

### ISSUE THREAD

**Issue by codehz** [InusualZ/SymbolExporter#1]
https://github.com/InusualZ/SymbolExporter/blob/master/src/Object.h#L12

I think you should remove and append `bool Object::commentMangledSymbol = false;` to Object.cpp

**Comment by InusualZ** [comment]
That's weird, what version of gcc are you using? I'm gonna do it any way.

**Comment by codehz** [comment]
@InusualZ 5.4
